public enum LoadingStatus
{
	Empty,
	WaitingForService,
	CheckingLobbyStatus,
	CleaningUpPreviousLobby,
	LeavingPreviousLobby,
	CreatingLobby,
	PreparingLobby,
	PreparingLobbyClient,
	WaitingForHostPlayer,
	ConnectingToGame,
	ConnectingToLobby,
	CreatingGame,
	GettingLobbyInformation,
	WaitingForSteam,
	WaitingForOtherPlayers,
	RequestingItemFromServer
}
